// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refactored.This.Data;

namespace Refactored.This.API.Migrations
{
    [DbContext(typeof(RefactorContext))]
    [Migration("20191230042232_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Refactored.This.Model.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StructureAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlFormSixtyTwo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            //modelBuilder.Entity("Refactored.This.Model.Entities.Product", b =>
            //    {
            //        b.Property<Guid>("Id")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("uniqueidentifier");

            //        b.Property<decimal>("DeliveryPrice")
            //            .HasColumnType("decimal(18,2)");

            //        b.Property<string>("Description")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("Name")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<decimal>("Price")
            //            .HasColumnType("decimal(18,2)");

            //        b.HasKey("Id");

            //        b.ToTable("Product");
            //    });

            //modelBuilder.Entity("Refactored.This.Model.Entities.ProductOption", b =>
            //    {
            //        b.Property<Guid>("Id")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("uniqueidentifier");

            //        b.Property<string>("Description")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("Name")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<Guid>("ProductId")
            //            .HasColumnType("uniqueidentifier");

            //        b.HasKey("Id");

            //        b.ToTable("ProductOption");
            //    });
#pragma warning restore 612, 618
        }
    }
}
